### ISSUE TITLE
Empty Exercises shouldn't be taken into account for the User Progress

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/scala-exercises#619]
It's happening in the new library https://github.com/scala-exercises/exercises-scalatutorial.

See #617 

![70d7cc4e-e2f4-11e6-840c-a1a539be6e64](https://cloud.githubusercontent.com/assets/4879373/22304354/5b52009a-e337-11e6-8fee-98b79eed080e.png)

**Comment by rafaparadela** [comment]
@juanpedromoreno Can you provide more information please? What do you mean with "Empty Exercises"?, I guess you mean an exercise with nothing to compile.

Instead of creating an empty exercise,  I would suggest to provide all the explanation as description of the next one. What do you think?

**Comment by juanpedromoreno** [comment]
Thread: https://github.com/scala-exercises/scala-exercises/pull/617#issuecomment-275077309

**Comment by anamariamv** [comment]
Fixed

**Comment by jrgonzalezg** [comment]
Is this deployed? The exercises mentioned on https://github.com/scala-exercises/exercises-scalatutorial/issues/5 still have problems.

**Comment by andys8** [comment]
`Exhaustivity` is not fixed
